name: Deploy to GCP VM

on:
  push:
    branches:
      - main # This will trigger the deployment on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

    - name: Add VM to known hosts
      run: ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

    - name: Deploy files to VM
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./index.html ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }}:/var/www/html
        # The command above copies all files from the repository to the specified directory on your VM.
        # Adjust the destination path `/var/www/html` as needed.
